// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CustomTrackLogger.proto

package com.javayh.agent.common.bean.proto;

public final class CustomTrackLoggerProto {
  private CustomTrackLoggerProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface CustomTrackLoggerOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.javayh.agent.common.bean.proto.CustomTrackLogger)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.com.javayh.agent.common.bean.proto.MessageType messageType = 1;</code>
     * @return The enum numeric value on the wire for messageType.
     */
    int getMessageTypeValue();
    /**
     * <code>.com.javayh.agent.common.bean.proto.MessageType messageType = 1;</code>
     * @return The messageType.
     */
    com.javayh.agent.common.bean.proto.MessageTypeProto.MessageType getMessageType();

    /**
     * <code>int64 id = 2;</code>
     * @return The id.
     */
    long getId();

    /**
     * <pre>
     **
     * 请求的trace id
     * </pre>
     *
     * <code>string traceId = 3;</code>
     * @return The traceId.
     */
    java.lang.String getTraceId();
    /**
     * <pre>
     **
     * 请求的trace id
     * </pre>
     *
     * <code>string traceId = 3;</code>
     * @return The bytes for traceId.
     */
    com.google.protobuf.ByteString
        getTraceIdBytes();

    /**
     * <pre>
     **
     * 实际业务的操作，比如 saveOrder ， updateOrder ，
     * </pre>
     *
     * <code>string operationType = 4;</code>
     * @return The operationType.
     */
    java.lang.String getOperationType();
    /**
     * <pre>
     **
     * 实际业务的操作，比如 saveOrder ， updateOrder ，
     * </pre>
     *
     * <code>string operationType = 4;</code>
     * @return The bytes for operationType.
     */
    com.google.protobuf.ByteString
        getOperationTypeBytes();

    /**
     * <pre>
     ** 请求的参数，string
     * </pre>
     *
     * <code>string requestParameter = 5;</code>
     * @return The requestParameter.
     */
    java.lang.String getRequestParameter();
    /**
     * <pre>
     ** 请求的参数，string
     * </pre>
     *
     * <code>string requestParameter = 5;</code>
     * @return The bytes for requestParameter.
     */
    com.google.protobuf.ByteString
        getRequestParameterBytes();

    /**
     * <pre>
     **
     * 服务的名字
     * </pre>
     *
     * <code>string appName = 6;</code>
     * @return The appName.
     */
    java.lang.String getAppName();
    /**
     * <pre>
     **
     * 服务的名字
     * </pre>
     *
     * <code>string appName = 6;</code>
     * @return The bytes for appName.
     */
    com.google.protobuf.ByteString
        getAppNameBytes();

    /**
     * <pre>
     **
     * 创建的时间
     * </pre>
     *
     * <code>.google.protobuf.Timestamp createTime = 7;</code>
     * @return Whether the createTime field is set.
     */
    boolean hasCreateTime();
    /**
     * <pre>
     **
     * 创建的时间
     * </pre>
     *
     * <code>.google.protobuf.Timestamp createTime = 7;</code>
     * @return The createTime.
     */
    com.google.protobuf.Timestamp getCreateTime();
    /**
     * <pre>
     **
     * 创建的时间
     * </pre>
     *
     * <code>.google.protobuf.Timestamp createTime = 7;</code>
     */
    com.google.protobuf.TimestampOrBuilder getCreateTimeOrBuilder();

    /**
     * <pre>
     **
     * 创建人
     * &lt;p&gt;
     * 这里需要结合自己的开发脚手架进行创建人
     * </pre>
     *
     * <code>string createBy = 8;</code>
     * @return The createBy.
     */
    java.lang.String getCreateBy();
    /**
     * <pre>
     **
     * 创建人
     * &lt;p&gt;
     * 这里需要结合自己的开发脚手架进行创建人
     * </pre>
     *
     * <code>string createBy = 8;</code>
     * @return The bytes for createBy.
     */
    com.google.protobuf.ByteString
        getCreateByBytes();

    /**
     * <pre>
     **
     * 异常信息
     * </pre>
     *
     * <code>string errorMsg = 9;</code>
     * @return The errorMsg.
     */
    java.lang.String getErrorMsg();
    /**
     * <pre>
     **
     * 异常信息
     * </pre>
     *
     * <code>string errorMsg = 9;</code>
     * @return The bytes for errorMsg.
     */
    com.google.protobuf.ByteString
        getErrorMsgBytes();

    /**
     * <pre>
     **
     * 是否忽略此消息，消息传递时判断是否需要继续向下传递
     * </pre>
     *
     * <code>bool ignore = 10;</code>
     * @return The ignore.
     */
    boolean getIgnore();
  }
  /**
   * Protobuf type {@code com.javayh.agent.common.bean.proto.CustomTrackLogger}
   */
  public static final class CustomTrackLogger extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.javayh.agent.common.bean.proto.CustomTrackLogger)
      CustomTrackLoggerOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use CustomTrackLogger.newBuilder() to construct.
    private CustomTrackLogger(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CustomTrackLogger() {
      messageType_ = 0;
      traceId_ = "";
      operationType_ = "";
      requestParameter_ = "";
      appName_ = "";
      createBy_ = "";
      errorMsg_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new CustomTrackLogger();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private CustomTrackLogger(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int rawValue = input.readEnum();

              messageType_ = rawValue;
              break;
            }
            case 16: {

              id_ = input.readInt64();
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              traceId_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              operationType_ = s;
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              requestParameter_ = s;
              break;
            }
            case 50: {
              java.lang.String s = input.readStringRequireUtf8();

              appName_ = s;
              break;
            }
            case 58: {
              com.google.protobuf.Timestamp.Builder subBuilder = null;
              if (createTime_ != null) {
                subBuilder = createTime_.toBuilder();
              }
              createTime_ = input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(createTime_);
                createTime_ = subBuilder.buildPartial();
              }

              break;
            }
            case 66: {
              java.lang.String s = input.readStringRequireUtf8();

              createBy_ = s;
              break;
            }
            case 74: {
              java.lang.String s = input.readStringRequireUtf8();

              errorMsg_ = s;
              break;
            }
            case 80: {

              ignore_ = input.readBool();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return CustomTrackLoggerProto.internal_static_com_javayh_agent_rpc_CustomTrackLogger_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return CustomTrackLoggerProto.internal_static_com_javayh_agent_rpc_CustomTrackLogger_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              CustomTrackLoggerProto.CustomTrackLogger.class, CustomTrackLoggerProto.CustomTrackLogger.Builder.class);
    }

    public interface KeyValuesOrBuilder extends
        // @@protoc_insertion_point(interface_extends:com.javayh.agent.common.bean.proto.CustomTrackLogger.KeyValues)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>string key = 1;</code>
       * @return The key.
       */
      java.lang.String getKey();
      /**
       * <code>string key = 1;</code>
       * @return The bytes for key.
       */
      com.google.protobuf.ByteString
          getKeyBytes();

      /**
       * <code>string value = 2;</code>
       * @return The value.
       */
      java.lang.String getValue();
      /**
       * <code>string value = 2;</code>
       * @return The bytes for value.
       */
      com.google.protobuf.ByteString
          getValueBytes();
    }
    /**
     * Protobuf type {@code com.javayh.agent.common.bean.proto.CustomTrackLogger.KeyValues}
     */
    public static final class KeyValues extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:com.javayh.agent.common.bean.proto.CustomTrackLogger.KeyValues)
        KeyValuesOrBuilder {
    private static final long serialVersionUID = 0L;
      // Use KeyValues.newBuilder() to construct.
      private KeyValues(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private KeyValues() {
        key_ = "";
        value_ = "";
      }

      @java.lang.Override
      @SuppressWarnings({"unused"})
      protected java.lang.Object newInstance(
          UnusedPrivateParameter unused) {
        return new KeyValues();
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return this.unknownFields;
      }
      private KeyValues(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                java.lang.String s = input.readStringRequireUtf8();

                key_ = s;
                break;
              }
              case 18: {
                java.lang.String s = input.readStringRequireUtf8();

                value_ = s;
                break;
              }
              default: {
                if (!parseUnknownField(
                    input, unknownFields, extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return CustomTrackLoggerProto.internal_static_com_javayh_agent_rpc_CustomTrackLogger_KeyValues_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return CustomTrackLoggerProto.internal_static_com_javayh_agent_rpc_CustomTrackLogger_KeyValues_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                CustomTrackLoggerProto.CustomTrackLogger.KeyValues.class, CustomTrackLoggerProto.CustomTrackLogger.KeyValues.Builder.class);
      }

      public static final int KEY_FIELD_NUMBER = 1;
      private volatile java.lang.Object key_;
      /**
       * <code>string key = 1;</code>
       * @return The key.
       */
      @java.lang.Override
      public java.lang.String getKey() {
        java.lang.Object ref = key_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          key_ = s;
          return s;
        }
      }
      /**
       * <code>string key = 1;</code>
       * @return The bytes for key.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getKeyBytes() {
        java.lang.Object ref = key_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          key_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int VALUE_FIELD_NUMBER = 2;
      private volatile java.lang.Object value_;
      /**
       * <code>string value = 2;</code>
       * @return The value.
       */
      @java.lang.Override
      public java.lang.String getValue() {
        java.lang.Object ref = value_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          value_ = s;
          return s;
        }
      }
      /**
       * <code>string value = 2;</code>
       * @return The bytes for value.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getValueBytes() {
        java.lang.Object ref = value_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          value_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      private byte memoizedIsInitialized = -1;
      @java.lang.Override
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      @java.lang.Override
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (!getKeyBytes().isEmpty()) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 1, key_);
        }
        if (!getValueBytes().isEmpty()) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 2, value_);
        }
        unknownFields.writeTo(output);
      }

      @java.lang.Override
      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (!getKeyBytes().isEmpty()) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, key_);
        }
        if (!getValueBytes().isEmpty()) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, value_);
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
      }

      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof CustomTrackLoggerProto.CustomTrackLogger.KeyValues)) {
          return super.equals(obj);
        }
        CustomTrackLoggerProto.CustomTrackLogger.KeyValues other = (CustomTrackLoggerProto.CustomTrackLogger.KeyValues) obj;

        if (!getKey()
            .equals(other.getKey())) return false;
        if (!getValue()
            .equals(other.getValue())) return false;
        if (!unknownFields.equals(other.unknownFields)) return false;
        return true;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + KEY_FIELD_NUMBER;
        hash = (53 * hash) + getKey().hashCode();
        hash = (37 * hash) + VALUE_FIELD_NUMBER;
        hash = (53 * hash) + getValue().hashCode();
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static CustomTrackLoggerProto.CustomTrackLogger.KeyValues parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static CustomTrackLoggerProto.CustomTrackLogger.KeyValues parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static CustomTrackLoggerProto.CustomTrackLogger.KeyValues parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static CustomTrackLoggerProto.CustomTrackLogger.KeyValues parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static CustomTrackLoggerProto.CustomTrackLogger.KeyValues parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static CustomTrackLoggerProto.CustomTrackLogger.KeyValues parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static CustomTrackLoggerProto.CustomTrackLogger.KeyValues parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static CustomTrackLoggerProto.CustomTrackLogger.KeyValues parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static CustomTrackLoggerProto.CustomTrackLogger.KeyValues parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static CustomTrackLoggerProto.CustomTrackLogger.KeyValues parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static CustomTrackLoggerProto.CustomTrackLogger.KeyValues parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static CustomTrackLoggerProto.CustomTrackLogger.KeyValues parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      @java.lang.Override
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(CustomTrackLoggerProto.CustomTrackLogger.KeyValues prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      @java.lang.Override
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code com.javayh.agent.common.bean.proto.CustomTrackLogger.KeyValues}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:com.javayh.agent.common.bean.proto.CustomTrackLogger.KeyValues)
          CustomTrackLoggerProto.CustomTrackLogger.KeyValuesOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return CustomTrackLoggerProto.internal_static_com_javayh_agent_rpc_CustomTrackLogger_KeyValues_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return CustomTrackLoggerProto.internal_static_com_javayh_agent_rpc_CustomTrackLogger_KeyValues_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  CustomTrackLoggerProto.CustomTrackLogger.KeyValues.class, CustomTrackLoggerProto.CustomTrackLogger.KeyValues.Builder.class);
        }

        // Construct using com.javayh.agent.common.bean.proto.CustomTrackLoggerProto.CustomTrackLogger.KeyValues.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3
                  .alwaysUseFieldBuilders) {
          }
        }
        @java.lang.Override
        public Builder clear() {
          super.clear();
          key_ = "";

          value_ = "";

          return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return CustomTrackLoggerProto.internal_static_com_javayh_agent_rpc_CustomTrackLogger_KeyValues_descriptor;
        }

        @java.lang.Override
        public CustomTrackLoggerProto.CustomTrackLogger.KeyValues getDefaultInstanceForType() {
          return CustomTrackLoggerProto.CustomTrackLogger.KeyValues.getDefaultInstance();
        }

        @java.lang.Override
        public CustomTrackLoggerProto.CustomTrackLogger.KeyValues build() {
          CustomTrackLoggerProto.CustomTrackLogger.KeyValues result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        @java.lang.Override
        public CustomTrackLoggerProto.CustomTrackLogger.KeyValues buildPartial() {
          CustomTrackLoggerProto.CustomTrackLogger.KeyValues result = new CustomTrackLoggerProto.CustomTrackLogger.KeyValues(this);
          result.key_ = key_;
          result.value_ = value_;
          onBuilt();
          return result;
        }

        @java.lang.Override
        public Builder clone() {
          return super.clone();
        }
        @java.lang.Override
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.setField(field, value);
        }
        @java.lang.Override
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return super.clearField(field);
        }
        @java.lang.Override
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return super.clearOneof(oneof);
        }
        @java.lang.Override
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, java.lang.Object value) {
          return super.setRepeatedField(field, index, value);
        }
        @java.lang.Override
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.addRepeatedField(field, value);
        }
        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof CustomTrackLoggerProto.CustomTrackLogger.KeyValues) {
            return mergeFrom((CustomTrackLoggerProto.CustomTrackLogger.KeyValues)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(CustomTrackLoggerProto.CustomTrackLogger.KeyValues other) {
          if (other == CustomTrackLoggerProto.CustomTrackLogger.KeyValues.getDefaultInstance()) return this;
          if (!other.getKey().isEmpty()) {
            key_ = other.key_;
            onChanged();
          }
          if (!other.getValue().isEmpty()) {
            value_ = other.value_;
            onChanged();
          }
          this.mergeUnknownFields(other.unknownFields);
          onChanged();
          return this;
        }

        @java.lang.Override
        public final boolean isInitialized() {
          return true;
        }

        @java.lang.Override
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          CustomTrackLoggerProto.CustomTrackLogger.KeyValues parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (CustomTrackLoggerProto.CustomTrackLogger.KeyValues) e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }

        private java.lang.Object key_ = "";
        /**
         * <code>string key = 1;</code>
         * @return The key.
         */
        public java.lang.String getKey() {
          java.lang.Object ref = key_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            key_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>string key = 1;</code>
         * @return The bytes for key.
         */
        public com.google.protobuf.ByteString
            getKeyBytes() {
          java.lang.Object ref = key_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            key_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>string key = 1;</code>
         * @param value The key to set.
         * @return This builder for chaining.
         */
        public Builder setKey(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  
          key_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>string key = 1;</code>
         * @return This builder for chaining.
         */
        public Builder clearKey() {
          
          key_ = getDefaultInstance().getKey();
          onChanged();
          return this;
        }
        /**
         * <code>string key = 1;</code>
         * @param value The bytes for key to set.
         * @return This builder for chaining.
         */
        public Builder setKeyBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
          
          key_ = value;
          onChanged();
          return this;
        }

        private java.lang.Object value_ = "";
        /**
         * <code>string value = 2;</code>
         * @return The value.
         */
        public java.lang.String getValue() {
          java.lang.Object ref = value_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            value_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>string value = 2;</code>
         * @return The bytes for value.
         */
        public com.google.protobuf.ByteString
            getValueBytes() {
          java.lang.Object ref = value_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            value_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>string value = 2;</code>
         * @param value The value to set.
         * @return This builder for chaining.
         */
        public Builder setValue(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  
          value_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>string value = 2;</code>
         * @return This builder for chaining.
         */
        public Builder clearValue() {
          
          value_ = getDefaultInstance().getValue();
          onChanged();
          return this;
        }
        /**
         * <code>string value = 2;</code>
         * @param value The bytes for value to set.
         * @return This builder for chaining.
         */
        public Builder setValueBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
          
          value_ = value;
          onChanged();
          return this;
        }
        @java.lang.Override
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.setUnknownFields(unknownFields);
        }

        @java.lang.Override
        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:com.javayh.agent.common.bean.proto.CustomTrackLogger.KeyValues)
      }

      // @@protoc_insertion_point(class_scope:com.javayh.agent.common.bean.proto.CustomTrackLogger.KeyValues)
      private static final CustomTrackLoggerProto.CustomTrackLogger.KeyValues DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new CustomTrackLoggerProto.CustomTrackLogger.KeyValues();
      }

      public static CustomTrackLoggerProto.CustomTrackLogger.KeyValues getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static final com.google.protobuf.Parser<KeyValues>
          PARSER = new com.google.protobuf.AbstractParser<KeyValues>() {
        @java.lang.Override
        public KeyValues parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new KeyValues(input, extensionRegistry);
        }
      };

      public static com.google.protobuf.Parser<KeyValues> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<KeyValues> getParserForType() {
        return PARSER;
      }

      @java.lang.Override
      public CustomTrackLoggerProto.CustomTrackLogger.KeyValues getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    public static final int MESSAGETYPE_FIELD_NUMBER = 1;
    private int messageType_;
    /**
     * <code>.com.javayh.agent.common.bean.proto.MessageType messageType = 1;</code>
     * @return The enum numeric value on the wire for messageType.
     */
    @java.lang.Override public int getMessageTypeValue() {
      return messageType_;
    }
    /**
     * <code>.com.javayh.agent.common.bean.proto.MessageType messageType = 1;</code>
     * @return The messageType.
     */
    @java.lang.Override public com.javayh.agent.common.bean.proto.MessageTypeProto.MessageType getMessageType() {
      @SuppressWarnings("deprecation")
      com.javayh.agent.common.bean.proto.MessageTypeProto.MessageType result = com.javayh.agent.common.bean.proto.MessageTypeProto.MessageType.valueOf(messageType_);
      return result == null ? com.javayh.agent.common.bean.proto.MessageTypeProto.MessageType.UNRECOGNIZED : result;
    }

    public static final int ID_FIELD_NUMBER = 2;
    private long id_;
    /**
     * <code>int64 id = 2;</code>
     * @return The id.
     */
    @java.lang.Override
    public long getId() {
      return id_;
    }

    public static final int TRACEID_FIELD_NUMBER = 3;
    private volatile java.lang.Object traceId_;
    /**
     * <pre>
     **
     * 请求的trace id
     * </pre>
     *
     * <code>string traceId = 3;</code>
     * @return The traceId.
     */
    @java.lang.Override
    public java.lang.String getTraceId() {
      java.lang.Object ref = traceId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        traceId_ = s;
        return s;
      }
    }
    /**
     * <pre>
     **
     * 请求的trace id
     * </pre>
     *
     * <code>string traceId = 3;</code>
     * @return The bytes for traceId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTraceIdBytes() {
      java.lang.Object ref = traceId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        traceId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int OPERATIONTYPE_FIELD_NUMBER = 4;
    private volatile java.lang.Object operationType_;
    /**
     * <pre>
     **
     * 实际业务的操作，比如 saveOrder ， updateOrder ，
     * </pre>
     *
     * <code>string operationType = 4;</code>
     * @return The operationType.
     */
    @java.lang.Override
    public java.lang.String getOperationType() {
      java.lang.Object ref = operationType_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        operationType_ = s;
        return s;
      }
    }
    /**
     * <pre>
     **
     * 实际业务的操作，比如 saveOrder ， updateOrder ，
     * </pre>
     *
     * <code>string operationType = 4;</code>
     * @return The bytes for operationType.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getOperationTypeBytes() {
      java.lang.Object ref = operationType_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        operationType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int REQUESTPARAMETER_FIELD_NUMBER = 5;
    private volatile java.lang.Object requestParameter_;
    /**
     * <pre>
     ** 请求的参数，string
     * </pre>
     *
     * <code>string requestParameter = 5;</code>
     * @return The requestParameter.
     */
    @java.lang.Override
    public java.lang.String getRequestParameter() {
      java.lang.Object ref = requestParameter_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        requestParameter_ = s;
        return s;
      }
    }
    /**
     * <pre>
     ** 请求的参数，string
     * </pre>
     *
     * <code>string requestParameter = 5;</code>
     * @return The bytes for requestParameter.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getRequestParameterBytes() {
      java.lang.Object ref = requestParameter_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        requestParameter_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int APPNAME_FIELD_NUMBER = 6;
    private volatile java.lang.Object appName_;
    /**
     * <pre>
     **
     * 服务的名字
     * </pre>
     *
     * <code>string appName = 6;</code>
     * @return The appName.
     */
    @java.lang.Override
    public java.lang.String getAppName() {
      java.lang.Object ref = appName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        appName_ = s;
        return s;
      }
    }
    /**
     * <pre>
     **
     * 服务的名字
     * </pre>
     *
     * <code>string appName = 6;</code>
     * @return The bytes for appName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getAppNameBytes() {
      java.lang.Object ref = appName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        appName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CREATETIME_FIELD_NUMBER = 7;
    private com.google.protobuf.Timestamp createTime_;
    /**
     * <pre>
     **
     * 创建的时间
     * </pre>
     *
     * <code>.google.protobuf.Timestamp createTime = 7;</code>
     * @return Whether the createTime field is set.
     */
    @java.lang.Override
    public boolean hasCreateTime() {
      return createTime_ != null;
    }
    /**
     * <pre>
     **
     * 创建的时间
     * </pre>
     *
     * <code>.google.protobuf.Timestamp createTime = 7;</code>
     * @return The createTime.
     */
    @java.lang.Override
    public com.google.protobuf.Timestamp getCreateTime() {
      return createTime_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : createTime_;
    }
    /**
     * <pre>
     **
     * 创建的时间
     * </pre>
     *
     * <code>.google.protobuf.Timestamp createTime = 7;</code>
     */
    @java.lang.Override
    public com.google.protobuf.TimestampOrBuilder getCreateTimeOrBuilder() {
      return getCreateTime();
    }

    public static final int CREATEBY_FIELD_NUMBER = 8;
    private volatile java.lang.Object createBy_;
    /**
     * <pre>
     **
     * 创建人
     * &lt;p&gt;
     * 这里需要结合自己的开发脚手架进行创建人
     * </pre>
     *
     * <code>string createBy = 8;</code>
     * @return The createBy.
     */
    @java.lang.Override
    public java.lang.String getCreateBy() {
      java.lang.Object ref = createBy_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        createBy_ = s;
        return s;
      }
    }
    /**
     * <pre>
     **
     * 创建人
     * &lt;p&gt;
     * 这里需要结合自己的开发脚手架进行创建人
     * </pre>
     *
     * <code>string createBy = 8;</code>
     * @return The bytes for createBy.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getCreateByBytes() {
      java.lang.Object ref = createBy_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        createBy_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ERRORMSG_FIELD_NUMBER = 9;
    private volatile java.lang.Object errorMsg_;
    /**
     * <pre>
     **
     * 异常信息
     * </pre>
     *
     * <code>string errorMsg = 9;</code>
     * @return The errorMsg.
     */
    @java.lang.Override
    public java.lang.String getErrorMsg() {
      java.lang.Object ref = errorMsg_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        errorMsg_ = s;
        return s;
      }
    }
    /**
     * <pre>
     **
     * 异常信息
     * </pre>
     *
     * <code>string errorMsg = 9;</code>
     * @return The bytes for errorMsg.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getErrorMsgBytes() {
      java.lang.Object ref = errorMsg_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        errorMsg_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int IGNORE_FIELD_NUMBER = 10;
    private boolean ignore_;
    /**
     * <pre>
     **
     * 是否忽略此消息，消息传递时判断是否需要继续向下传递
     * </pre>
     *
     * <code>bool ignore = 10;</code>
     * @return The ignore.
     */
    @java.lang.Override
    public boolean getIgnore() {
      return ignore_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (messageType_ != com.javayh.agent.common.bean.proto.MessageTypeProto.MessageType.LOGGER_COLLECTOR.getNumber()) {
        output.writeEnum(1, messageType_);
      }
      if (id_ != 0L) {
        output.writeInt64(2, id_);
      }
      if (!getTraceIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, traceId_);
      }
      if (!getOperationTypeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, operationType_);
      }
      if (!getRequestParameterBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, requestParameter_);
      }
      if (!getAppNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, appName_);
      }
      if (createTime_ != null) {
        output.writeMessage(7, getCreateTime());
      }
      if (!getCreateByBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 8, createBy_);
      }
      if (!getErrorMsgBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 9, errorMsg_);
      }
      if (ignore_ != false) {
        output.writeBool(10, ignore_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (messageType_ != com.javayh.agent.common.bean.proto.MessageTypeProto.MessageType.LOGGER_COLLECTOR.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, messageType_);
      }
      if (id_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, id_);
      }
      if (!getTraceIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, traceId_);
      }
      if (!getOperationTypeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, operationType_);
      }
      if (!getRequestParameterBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, requestParameter_);
      }
      if (!getAppNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, appName_);
      }
      if (createTime_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(7, getCreateTime());
      }
      if (!getCreateByBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, createBy_);
      }
      if (!getErrorMsgBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, errorMsg_);
      }
      if (ignore_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(10, ignore_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof CustomTrackLoggerProto.CustomTrackLogger)) {
        return super.equals(obj);
      }
      CustomTrackLoggerProto.CustomTrackLogger other = (CustomTrackLoggerProto.CustomTrackLogger) obj;

      if (messageType_ != other.messageType_) return false;
      if (getId()
          != other.getId()) return false;
      if (!getTraceId()
          .equals(other.getTraceId())) return false;
      if (!getOperationType()
          .equals(other.getOperationType())) return false;
      if (!getRequestParameter()
          .equals(other.getRequestParameter())) return false;
      if (!getAppName()
          .equals(other.getAppName())) return false;
      if (hasCreateTime() != other.hasCreateTime()) return false;
      if (hasCreateTime()) {
        if (!getCreateTime()
            .equals(other.getCreateTime())) return false;
      }
      if (!getCreateBy()
          .equals(other.getCreateBy())) return false;
      if (!getErrorMsg()
          .equals(other.getErrorMsg())) return false;
      if (getIgnore()
          != other.getIgnore()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + MESSAGETYPE_FIELD_NUMBER;
      hash = (53 * hash) + messageType_;
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getId());
      hash = (37 * hash) + TRACEID_FIELD_NUMBER;
      hash = (53 * hash) + getTraceId().hashCode();
      hash = (37 * hash) + OPERATIONTYPE_FIELD_NUMBER;
      hash = (53 * hash) + getOperationType().hashCode();
      hash = (37 * hash) + REQUESTPARAMETER_FIELD_NUMBER;
      hash = (53 * hash) + getRequestParameter().hashCode();
      hash = (37 * hash) + APPNAME_FIELD_NUMBER;
      hash = (53 * hash) + getAppName().hashCode();
      if (hasCreateTime()) {
        hash = (37 * hash) + CREATETIME_FIELD_NUMBER;
        hash = (53 * hash) + getCreateTime().hashCode();
      }
      hash = (37 * hash) + CREATEBY_FIELD_NUMBER;
      hash = (53 * hash) + getCreateBy().hashCode();
      hash = (37 * hash) + ERRORMSG_FIELD_NUMBER;
      hash = (53 * hash) + getErrorMsg().hashCode();
      hash = (37 * hash) + IGNORE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getIgnore());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static CustomTrackLoggerProto.CustomTrackLogger parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static CustomTrackLoggerProto.CustomTrackLogger parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static CustomTrackLoggerProto.CustomTrackLogger parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static CustomTrackLoggerProto.CustomTrackLogger parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static CustomTrackLoggerProto.CustomTrackLogger parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static CustomTrackLoggerProto.CustomTrackLogger parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static CustomTrackLoggerProto.CustomTrackLogger parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static CustomTrackLoggerProto.CustomTrackLogger parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static CustomTrackLoggerProto.CustomTrackLogger parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static CustomTrackLoggerProto.CustomTrackLogger parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static CustomTrackLoggerProto.CustomTrackLogger parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static CustomTrackLoggerProto.CustomTrackLogger parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(CustomTrackLoggerProto.CustomTrackLogger prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.javayh.agent.common.bean.proto.CustomTrackLogger}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.javayh.agent.common.bean.proto.CustomTrackLogger)
        CustomTrackLoggerProto.CustomTrackLoggerOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return CustomTrackLoggerProto.internal_static_com_javayh_agent_rpc_CustomTrackLogger_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return CustomTrackLoggerProto.internal_static_com_javayh_agent_rpc_CustomTrackLogger_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                CustomTrackLoggerProto.CustomTrackLogger.class, CustomTrackLoggerProto.CustomTrackLogger.Builder.class);
      }

      // Construct using com.javayh.agent.common.bean.proto.CustomTrackLoggerProto.CustomTrackLogger.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        messageType_ = 0;

        id_ = 0L;

        traceId_ = "";

        operationType_ = "";

        requestParameter_ = "";

        appName_ = "";

        if (createTimeBuilder_ == null) {
          createTime_ = null;
        } else {
          createTime_ = null;
          createTimeBuilder_ = null;
        }
        createBy_ = "";

        errorMsg_ = "";

        ignore_ = false;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return CustomTrackLoggerProto.internal_static_com_javayh_agent_rpc_CustomTrackLogger_descriptor;
      }

      @java.lang.Override
      public CustomTrackLoggerProto.CustomTrackLogger getDefaultInstanceForType() {
        return CustomTrackLoggerProto.CustomTrackLogger.getDefaultInstance();
      }

      @java.lang.Override
      public CustomTrackLoggerProto.CustomTrackLogger build() {
        CustomTrackLoggerProto.CustomTrackLogger result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public CustomTrackLoggerProto.CustomTrackLogger buildPartial() {
        CustomTrackLoggerProto.CustomTrackLogger result = new CustomTrackLoggerProto.CustomTrackLogger(this);
        result.messageType_ = messageType_;
        result.id_ = id_;
        result.traceId_ = traceId_;
        result.operationType_ = operationType_;
        result.requestParameter_ = requestParameter_;
        result.appName_ = appName_;
        if (createTimeBuilder_ == null) {
          result.createTime_ = createTime_;
        } else {
          result.createTime_ = createTimeBuilder_.build();
        }
        result.createBy_ = createBy_;
        result.errorMsg_ = errorMsg_;
        result.ignore_ = ignore_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof CustomTrackLoggerProto.CustomTrackLogger) {
          return mergeFrom((CustomTrackLoggerProto.CustomTrackLogger)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(CustomTrackLoggerProto.CustomTrackLogger other) {
        if (other == CustomTrackLoggerProto.CustomTrackLogger.getDefaultInstance()) return this;
        if (other.messageType_ != 0) {
          setMessageTypeValue(other.getMessageTypeValue());
        }
        if (other.getId() != 0L) {
          setId(other.getId());
        }
        if (!other.getTraceId().isEmpty()) {
          traceId_ = other.traceId_;
          onChanged();
        }
        if (!other.getOperationType().isEmpty()) {
          operationType_ = other.operationType_;
          onChanged();
        }
        if (!other.getRequestParameter().isEmpty()) {
          requestParameter_ = other.requestParameter_;
          onChanged();
        }
        if (!other.getAppName().isEmpty()) {
          appName_ = other.appName_;
          onChanged();
        }
        if (other.hasCreateTime()) {
          mergeCreateTime(other.getCreateTime());
        }
        if (!other.getCreateBy().isEmpty()) {
          createBy_ = other.createBy_;
          onChanged();
        }
        if (!other.getErrorMsg().isEmpty()) {
          errorMsg_ = other.errorMsg_;
          onChanged();
        }
        if (other.getIgnore() != false) {
          setIgnore(other.getIgnore());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        CustomTrackLoggerProto.CustomTrackLogger parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (CustomTrackLoggerProto.CustomTrackLogger) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int messageType_ = 0;
      /**
       * <code>.com.javayh.agent.common.bean.proto.MessageType messageType = 1;</code>
       * @return The enum numeric value on the wire for messageType.
       */
      @java.lang.Override public int getMessageTypeValue() {
        return messageType_;
      }
      /**
       * <code>.com.javayh.agent.common.bean.proto.MessageType messageType = 1;</code>
       * @param value The enum numeric value on the wire for messageType to set.
       * @return This builder for chaining.
       */
      public Builder setMessageTypeValue(int value) {
        
        messageType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.com.javayh.agent.common.bean.proto.MessageType messageType = 1;</code>
       * @return The messageType.
       */
      @java.lang.Override
      public com.javayh.agent.common.bean.proto.MessageTypeProto.MessageType getMessageType() {
        @SuppressWarnings("deprecation")
        com.javayh.agent.common.bean.proto.MessageTypeProto.MessageType result = com.javayh.agent.common.bean.proto.MessageTypeProto.MessageType.valueOf(messageType_);
        return result == null ? com.javayh.agent.common.bean.proto.MessageTypeProto.MessageType.UNRECOGNIZED : result;
      }
      /**
       * <code>.com.javayh.agent.common.bean.proto.MessageType messageType = 1;</code>
       * @param value The messageType to set.
       * @return This builder for chaining.
       */
      public Builder setMessageType(com.javayh.agent.common.bean.proto.MessageTypeProto.MessageType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        messageType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.com.javayh.agent.common.bean.proto.MessageType messageType = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearMessageType() {
        
        messageType_ = 0;
        onChanged();
        return this;
      }

      private long id_ ;
      /**
       * <code>int64 id = 2;</code>
       * @return The id.
       */
      @java.lang.Override
      public long getId() {
        return id_;
      }
      /**
       * <code>int64 id = 2;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(long value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 id = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        
        id_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object traceId_ = "";
      /**
       * <pre>
       **
       * 请求的trace id
       * </pre>
       *
       * <code>string traceId = 3;</code>
       * @return The traceId.
       */
      public java.lang.String getTraceId() {
        java.lang.Object ref = traceId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          traceId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       **
       * 请求的trace id
       * </pre>
       *
       * <code>string traceId = 3;</code>
       * @return The bytes for traceId.
       */
      public com.google.protobuf.ByteString
          getTraceIdBytes() {
        java.lang.Object ref = traceId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          traceId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       **
       * 请求的trace id
       * </pre>
       *
       * <code>string traceId = 3;</code>
       * @param value The traceId to set.
       * @return This builder for chaining.
       */
      public Builder setTraceId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        traceId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       **
       * 请求的trace id
       * </pre>
       *
       * <code>string traceId = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearTraceId() {
        
        traceId_ = getDefaultInstance().getTraceId();
        onChanged();
        return this;
      }
      /**
       * <pre>
       **
       * 请求的trace id
       * </pre>
       *
       * <code>string traceId = 3;</code>
       * @param value The bytes for traceId to set.
       * @return This builder for chaining.
       */
      public Builder setTraceIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        traceId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object operationType_ = "";
      /**
       * <pre>
       **
       * 实际业务的操作，比如 saveOrder ， updateOrder ，
       * </pre>
       *
       * <code>string operationType = 4;</code>
       * @return The operationType.
       */
      public java.lang.String getOperationType() {
        java.lang.Object ref = operationType_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          operationType_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       **
       * 实际业务的操作，比如 saveOrder ， updateOrder ，
       * </pre>
       *
       * <code>string operationType = 4;</code>
       * @return The bytes for operationType.
       */
      public com.google.protobuf.ByteString
          getOperationTypeBytes() {
        java.lang.Object ref = operationType_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          operationType_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       **
       * 实际业务的操作，比如 saveOrder ， updateOrder ，
       * </pre>
       *
       * <code>string operationType = 4;</code>
       * @param value The operationType to set.
       * @return This builder for chaining.
       */
      public Builder setOperationType(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        operationType_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       **
       * 实际业务的操作，比如 saveOrder ， updateOrder ，
       * </pre>
       *
       * <code>string operationType = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearOperationType() {
        
        operationType_ = getDefaultInstance().getOperationType();
        onChanged();
        return this;
      }
      /**
       * <pre>
       **
       * 实际业务的操作，比如 saveOrder ， updateOrder ，
       * </pre>
       *
       * <code>string operationType = 4;</code>
       * @param value The bytes for operationType to set.
       * @return This builder for chaining.
       */
      public Builder setOperationTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        operationType_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object requestParameter_ = "";
      /**
       * <pre>
       ** 请求的参数，string
       * </pre>
       *
       * <code>string requestParameter = 5;</code>
       * @return The requestParameter.
       */
      public java.lang.String getRequestParameter() {
        java.lang.Object ref = requestParameter_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          requestParameter_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       ** 请求的参数，string
       * </pre>
       *
       * <code>string requestParameter = 5;</code>
       * @return The bytes for requestParameter.
       */
      public com.google.protobuf.ByteString
          getRequestParameterBytes() {
        java.lang.Object ref = requestParameter_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          requestParameter_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       ** 请求的参数，string
       * </pre>
       *
       * <code>string requestParameter = 5;</code>
       * @param value The requestParameter to set.
       * @return This builder for chaining.
       */
      public Builder setRequestParameter(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        requestParameter_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       ** 请求的参数，string
       * </pre>
       *
       * <code>string requestParameter = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearRequestParameter() {
        
        requestParameter_ = getDefaultInstance().getRequestParameter();
        onChanged();
        return this;
      }
      /**
       * <pre>
       ** 请求的参数，string
       * </pre>
       *
       * <code>string requestParameter = 5;</code>
       * @param value The bytes for requestParameter to set.
       * @return This builder for chaining.
       */
      public Builder setRequestParameterBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        requestParameter_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object appName_ = "";
      /**
       * <pre>
       **
       * 服务的名字
       * </pre>
       *
       * <code>string appName = 6;</code>
       * @return The appName.
       */
      public java.lang.String getAppName() {
        java.lang.Object ref = appName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          appName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       **
       * 服务的名字
       * </pre>
       *
       * <code>string appName = 6;</code>
       * @return The bytes for appName.
       */
      public com.google.protobuf.ByteString
          getAppNameBytes() {
        java.lang.Object ref = appName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          appName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       **
       * 服务的名字
       * </pre>
       *
       * <code>string appName = 6;</code>
       * @param value The appName to set.
       * @return This builder for chaining.
       */
      public Builder setAppName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        appName_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       **
       * 服务的名字
       * </pre>
       *
       * <code>string appName = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearAppName() {
        
        appName_ = getDefaultInstance().getAppName();
        onChanged();
        return this;
      }
      /**
       * <pre>
       **
       * 服务的名字
       * </pre>
       *
       * <code>string appName = 6;</code>
       * @param value The bytes for appName to set.
       * @return This builder for chaining.
       */
      public Builder setAppNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        appName_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.Timestamp createTime_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> createTimeBuilder_;
      /**
       * <pre>
       **
       * 创建的时间
       * </pre>
       *
       * <code>.google.protobuf.Timestamp createTime = 7;</code>
       * @return Whether the createTime field is set.
       */
      public boolean hasCreateTime() {
        return createTimeBuilder_ != null || createTime_ != null;
      }
      /**
       * <pre>
       **
       * 创建的时间
       * </pre>
       *
       * <code>.google.protobuf.Timestamp createTime = 7;</code>
       * @return The createTime.
       */
      public com.google.protobuf.Timestamp getCreateTime() {
        if (createTimeBuilder_ == null) {
          return createTime_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : createTime_;
        } else {
          return createTimeBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       **
       * 创建的时间
       * </pre>
       *
       * <code>.google.protobuf.Timestamp createTime = 7;</code>
       */
      public Builder setCreateTime(com.google.protobuf.Timestamp value) {
        if (createTimeBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          createTime_ = value;
          onChanged();
        } else {
          createTimeBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <pre>
       **
       * 创建的时间
       * </pre>
       *
       * <code>.google.protobuf.Timestamp createTime = 7;</code>
       */
      public Builder setCreateTime(
          com.google.protobuf.Timestamp.Builder builderForValue) {
        if (createTimeBuilder_ == null) {
          createTime_ = builderForValue.build();
          onChanged();
        } else {
          createTimeBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <pre>
       **
       * 创建的时间
       * </pre>
       *
       * <code>.google.protobuf.Timestamp createTime = 7;</code>
       */
      public Builder mergeCreateTime(com.google.protobuf.Timestamp value) {
        if (createTimeBuilder_ == null) {
          if (createTime_ != null) {
            createTime_ =
              com.google.protobuf.Timestamp.newBuilder(createTime_).mergeFrom(value).buildPartial();
          } else {
            createTime_ = value;
          }
          onChanged();
        } else {
          createTimeBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <pre>
       **
       * 创建的时间
       * </pre>
       *
       * <code>.google.protobuf.Timestamp createTime = 7;</code>
       */
      public Builder clearCreateTime() {
        if (createTimeBuilder_ == null) {
          createTime_ = null;
          onChanged();
        } else {
          createTime_ = null;
          createTimeBuilder_ = null;
        }

        return this;
      }
      /**
       * <pre>
       **
       * 创建的时间
       * </pre>
       *
       * <code>.google.protobuf.Timestamp createTime = 7;</code>
       */
      public com.google.protobuf.Timestamp.Builder getCreateTimeBuilder() {
        
        onChanged();
        return getCreateTimeFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       **
       * 创建的时间
       * </pre>
       *
       * <code>.google.protobuf.Timestamp createTime = 7;</code>
       */
      public com.google.protobuf.TimestampOrBuilder getCreateTimeOrBuilder() {
        if (createTimeBuilder_ != null) {
          return createTimeBuilder_.getMessageOrBuilder();
        } else {
          return createTime_ == null ?
              com.google.protobuf.Timestamp.getDefaultInstance() : createTime_;
        }
      }
      /**
       * <pre>
       **
       * 创建的时间
       * </pre>
       *
       * <code>.google.protobuf.Timestamp createTime = 7;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
          getCreateTimeFieldBuilder() {
        if (createTimeBuilder_ == null) {
          createTimeBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                  getCreateTime(),
                  getParentForChildren(),
                  isClean());
          createTime_ = null;
        }
        return createTimeBuilder_;
      }

      private java.lang.Object createBy_ = "";
      /**
       * <pre>
       **
       * 创建人
       * &lt;p&gt;
       * 这里需要结合自己的开发脚手架进行创建人
       * </pre>
       *
       * <code>string createBy = 8;</code>
       * @return The createBy.
       */
      public java.lang.String getCreateBy() {
        java.lang.Object ref = createBy_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          createBy_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       **
       * 创建人
       * &lt;p&gt;
       * 这里需要结合自己的开发脚手架进行创建人
       * </pre>
       *
       * <code>string createBy = 8;</code>
       * @return The bytes for createBy.
       */
      public com.google.protobuf.ByteString
          getCreateByBytes() {
        java.lang.Object ref = createBy_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          createBy_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       **
       * 创建人
       * &lt;p&gt;
       * 这里需要结合自己的开发脚手架进行创建人
       * </pre>
       *
       * <code>string createBy = 8;</code>
       * @param value The createBy to set.
       * @return This builder for chaining.
       */
      public Builder setCreateBy(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        createBy_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       **
       * 创建人
       * &lt;p&gt;
       * 这里需要结合自己的开发脚手架进行创建人
       * </pre>
       *
       * <code>string createBy = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearCreateBy() {
        
        createBy_ = getDefaultInstance().getCreateBy();
        onChanged();
        return this;
      }
      /**
       * <pre>
       **
       * 创建人
       * &lt;p&gt;
       * 这里需要结合自己的开发脚手架进行创建人
       * </pre>
       *
       * <code>string createBy = 8;</code>
       * @param value The bytes for createBy to set.
       * @return This builder for chaining.
       */
      public Builder setCreateByBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        createBy_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object errorMsg_ = "";
      /**
       * <pre>
       **
       * 异常信息
       * </pre>
       *
       * <code>string errorMsg = 9;</code>
       * @return The errorMsg.
       */
      public java.lang.String getErrorMsg() {
        java.lang.Object ref = errorMsg_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          errorMsg_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       **
       * 异常信息
       * </pre>
       *
       * <code>string errorMsg = 9;</code>
       * @return The bytes for errorMsg.
       */
      public com.google.protobuf.ByteString
          getErrorMsgBytes() {
        java.lang.Object ref = errorMsg_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          errorMsg_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       **
       * 异常信息
       * </pre>
       *
       * <code>string errorMsg = 9;</code>
       * @param value The errorMsg to set.
       * @return This builder for chaining.
       */
      public Builder setErrorMsg(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        errorMsg_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       **
       * 异常信息
       * </pre>
       *
       * <code>string errorMsg = 9;</code>
       * @return This builder for chaining.
       */
      public Builder clearErrorMsg() {
        
        errorMsg_ = getDefaultInstance().getErrorMsg();
        onChanged();
        return this;
      }
      /**
       * <pre>
       **
       * 异常信息
       * </pre>
       *
       * <code>string errorMsg = 9;</code>
       * @param value The bytes for errorMsg to set.
       * @return This builder for chaining.
       */
      public Builder setErrorMsgBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        errorMsg_ = value;
        onChanged();
        return this;
      }

      private boolean ignore_ ;
      /**
       * <pre>
       **
       * 是否忽略此消息，消息传递时判断是否需要继续向下传递
       * </pre>
       *
       * <code>bool ignore = 10;</code>
       * @return The ignore.
       */
      @java.lang.Override
      public boolean getIgnore() {
        return ignore_;
      }
      /**
       * <pre>
       **
       * 是否忽略此消息，消息传递时判断是否需要继续向下传递
       * </pre>
       *
       * <code>bool ignore = 10;</code>
       * @param value The ignore to set.
       * @return This builder for chaining.
       */
      public Builder setIgnore(boolean value) {
        
        ignore_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       **
       * 是否忽略此消息，消息传递时判断是否需要继续向下传递
       * </pre>
       *
       * <code>bool ignore = 10;</code>
       * @return This builder for chaining.
       */
      public Builder clearIgnore() {
        
        ignore_ = false;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.javayh.agent.common.bean.proto.CustomTrackLogger)
    }

    // @@protoc_insertion_point(class_scope:com.javayh.agent.common.bean.proto.CustomTrackLogger)
    private static final CustomTrackLoggerProto.CustomTrackLogger DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new CustomTrackLoggerProto.CustomTrackLogger();
    }

    public static CustomTrackLoggerProto.CustomTrackLogger getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CustomTrackLogger>
        PARSER = new com.google.protobuf.AbstractParser<CustomTrackLogger>() {
      @java.lang.Override
      public CustomTrackLogger parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CustomTrackLogger(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CustomTrackLogger> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CustomTrackLogger> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public CustomTrackLoggerProto.CustomTrackLogger getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_javayh_agent_rpc_CustomTrackLogger_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_javayh_agent_rpc_CustomTrackLogger_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_javayh_agent_rpc_CustomTrackLogger_KeyValues_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_javayh_agent_rpc_CustomTrackLogger_KeyValues_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\027CustomTrackLogger.proto\022\024com.javayh.ag" +
      "ent.rpc\032\037google/protobuf/timestamp.proto" +
      "\032\021MessageType.proto\"\267\002\n\021CustomTrackLogge" +
      "r\0226\n\013messageType\030\001 \001(\0162!.com.javayh.agen" +
      "t.rpc.MessageType\022\n\n\002id\030\002 \001(\003\022\017\n\007traceId" +
      "\030\003 \001(\t\022\025\n\roperationType\030\004 \001(\t\022\030\n\020request" +
      "Parameter\030\005 \001(\t\022\017\n\007appName\030\006 \001(\t\022.\n\ncrea" +
      "teTime\030\007 \001(\0132\032.google.protobuf.Timestamp" +
      "\022\020\n\010createBy\030\010 \001(\t\022\020\n\010errorMsg\030\t \001(\t\022\016\n\006" +
      "ignore\030\n \001(\010\032\'\n\tKeyValues\022\013\n\003key\030\001 \001(\t\022\r" +
      "\n\005value\030\002 \001(\tB\030B\026CustomTrackLoggerProtob" +
      "\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
          com.javayh.agent.common.bean.proto.MessageTypeProto.getDescriptor(),
        });
    internal_static_com_javayh_agent_rpc_CustomTrackLogger_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_javayh_agent_rpc_CustomTrackLogger_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_javayh_agent_rpc_CustomTrackLogger_descriptor,
        new java.lang.String[] { "MessageType", "Id", "TraceId", "OperationType", "RequestParameter", "AppName", "CreateTime", "CreateBy", "ErrorMsg", "Ignore", });
    internal_static_com_javayh_agent_rpc_CustomTrackLogger_KeyValues_descriptor =
      internal_static_com_javayh_agent_rpc_CustomTrackLogger_descriptor.getNestedTypes().get(0);
    internal_static_com_javayh_agent_rpc_CustomTrackLogger_KeyValues_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_javayh_agent_rpc_CustomTrackLogger_KeyValues_descriptor,
        new java.lang.String[] { "Key", "Value", });
    com.google.protobuf.TimestampProto.getDescriptor();
    com.javayh.agent.common.bean.proto.MessageTypeProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
