// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MessageBody.proto

package com.javayh.agent.common.bean.proto;

public final class MessageBodyProto {
    private MessageBodyProto() {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
                (com.google.protobuf.ExtensionRegistryLite) registry);
    }

    public interface MessageBodyOrBuilder extends
            // @@protoc_insertion_point(interface_extends:com.javayh.agent.rpc.MessageBody)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <pre>
         * 消息类型字段
         * </pre>
         *
         * <code>.com.javayh.agent.rpc.MessageType type = 2;</code>
         *
         * @return The enum numeric value on the wire for type.
         */
        int getTypeValue();

        /**
         * <pre>
         * 消息类型字段
         * </pre>
         *
         * <code>.com.javayh.agent.rpc.MessageType type = 2;</code>
         *
         * @return The type.
         */
        MessageTypeProto.MessageType getType();

        /**
         * <pre>
         * *服务标识
         * </pre>
         *
         * <code>int64 msgId = 3;</code>
         *
         * @return The msgId.
         */
        long getMsgId();

        /**
         * <pre>
         * *发送的消息
         * </pre>
         *
         * <code>string msg = 4;</code>
         *
         * @return The msg.
         */
        java.lang.String getMsg();

        /**
         * <pre>
         * *发送的消息
         * </pre>
         *
         * <code>string msg = 4;</code>
         *
         * @return The bytes for msg.
         */
        com.google.protobuf.ByteString
        getMsgBytes();

        /**
         * <pre>
         * *服务名
         * </pre>
         *
         * <code>string onlineAppName = 5;</code>
         *
         * @return The onlineAppName.
         */
        java.lang.String getOnlineAppName();

        /**
         * <pre>
         * *服务名
         * </pre>
         *
         * <code>string onlineAppName = 5;</code>
         *
         * @return The bytes for onlineAppName.
         */
        com.google.protobuf.ByteString
        getOnlineAppNameBytes();

        /**
         * <pre>
         * *接受消息的时间
         * </pre>
         *
         * <code>.google.protobuf.Timestamp onlineDate = 6;</code>
         *
         * @return Whether the onlineDate field is set.
         */
        boolean hasOnlineDate();

        /**
         * <pre>
         * *接受消息的时间
         * </pre>
         *
         * <code>.google.protobuf.Timestamp onlineDate = 6;</code>
         *
         * @return The onlineDate.
         */
        com.google.protobuf.Timestamp getOnlineDate();

        /**
         * <pre>
         * *接受消息的时间
         * </pre>
         *
         * <code>.google.protobuf.Timestamp onlineDate = 6;</code>
         */
        com.google.protobuf.TimestampOrBuilder getOnlineDateOrBuilder();

        /**
         * <pre>
         * *是否上线
         * </pre>
         *
         * <code>bool isActive = 7;</code>
         *
         * @return The isActive.
         */
        boolean getIsActive();
    }

    /**
     * Protobuf type {@code com.javayh.agent.rpc.MessageBody}
     */
    public static final class MessageBody extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:com.javayh.agent.rpc.MessageBody)
            MessageBodyOrBuilder {
        private static final long serialVersionUID = 0L;

        // Use MessageBody.newBuilder() to construct.
        private MessageBody(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }

        private MessageBody() {
            type_ = 0;
            msg_ = "";
            onlineAppName_ = "";
        }

        @java.lang.Override
        @SuppressWarnings({"unused"})
        protected java.lang.Object newInstance(
                UnusedPrivateParameter unused) {
            return new MessageBody();
        }

        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return this.unknownFields;
        }

        private MessageBody(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            if (extensionRegistry == null) {
                throw new java.lang.NullPointerException();
            }
            com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                    com.google.protobuf.UnknownFieldSet.newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        case 16: {
                            int rawValue = input.readEnum();

                            type_ = rawValue;
                            break;
                        }
                        case 24: {

                            msgId_ = input.readInt64();
                            break;
                        }
                        case 34: {
                            java.lang.String s = input.readStringRequireUtf8();

                            msg_ = s;
                            break;
                        }
                        case 42: {
                            java.lang.String s = input.readStringRequireUtf8();

                            onlineAppName_ = s;
                            break;
                        }
                        case 50: {
                            com.google.protobuf.Timestamp.Builder subBuilder = null;
                            if (onlineDate_ != null) {
                                subBuilder = onlineDate_.toBuilder();
                            }
                            onlineDate_ = input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
                            if (subBuilder != null) {
                                subBuilder.mergeFrom(onlineDate_);
                                onlineDate_ = subBuilder.buildPartial();
                            }

                            break;
                        }
                        case 56: {

                            isActive_ = input.readBool();
                            break;
                        }
                        default: {
                            if (!parseUnknownField(
                                    input, unknownFields, extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e).setUnfinishedMessage(this);
            } finally {
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return MessageBodyProto.internal_static_com_javayh_agent_rpc_MessageBody_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return MessageBodyProto.internal_static_com_javayh_agent_rpc_MessageBody_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            MessageBodyProto.MessageBody.class, MessageBodyProto.MessageBody.Builder.class);
        }

        public static final int TYPE_FIELD_NUMBER = 2;
        private int type_;

        /**
         * <pre>
         * 消息类型字段
         * </pre>
         *
         * <code>.com.javayh.agent.rpc.MessageType type = 2;</code>
         *
         * @return The enum numeric value on the wire for type.
         */
        @java.lang.Override
        public int getTypeValue() {
            return type_;
        }

        /**
         * <pre>
         * 消息类型字段
         * </pre>
         *
         * <code>.com.javayh.agent.rpc.MessageType type = 2;</code>
         *
         * @return The type.
         */
        @java.lang.Override
        public MessageTypeProto.MessageType getType() {
            @SuppressWarnings("deprecation")
            MessageTypeProto.MessageType result = MessageTypeProto.MessageType.valueOf(type_);
            return result == null ? MessageTypeProto.MessageType.UNRECOGNIZED : result;
        }

        public static final int MSGID_FIELD_NUMBER = 3;
        private long msgId_;

        /**
         * <pre>
         * *服务标识
         * </pre>
         *
         * <code>int64 msgId = 3;</code>
         *
         * @return The msgId.
         */
        @java.lang.Override
        public long getMsgId() {
            return msgId_;
        }

        public static final int MSG_FIELD_NUMBER = 4;
        private volatile java.lang.Object msg_;

        /**
         * <pre>
         * *发送的消息
         * </pre>
         *
         * <code>string msg = 4;</code>
         *
         * @return The msg.
         */
        @java.lang.Override
        public java.lang.String getMsg() {
            java.lang.Object ref = msg_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                msg_ = s;
                return s;
            }
        }

        /**
         * <pre>
         * *发送的消息
         * </pre>
         *
         * <code>string msg = 4;</code>
         *
         * @return The bytes for msg.
         */
        @java.lang.Override
        public com.google.protobuf.ByteString
        getMsgBytes() {
            java.lang.Object ref = msg_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                msg_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int ONLINEAPPNAME_FIELD_NUMBER = 5;
        private volatile java.lang.Object onlineAppName_;

        /**
         * <pre>
         * *服务名
         * </pre>
         *
         * <code>string onlineAppName = 5;</code>
         *
         * @return The onlineAppName.
         */
        @java.lang.Override
        public java.lang.String getOnlineAppName() {
            java.lang.Object ref = onlineAppName_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                onlineAppName_ = s;
                return s;
            }
        }

        /**
         * <pre>
         * *服务名
         * </pre>
         *
         * <code>string onlineAppName = 5;</code>
         *
         * @return The bytes for onlineAppName.
         */
        @java.lang.Override
        public com.google.protobuf.ByteString
        getOnlineAppNameBytes() {
            java.lang.Object ref = onlineAppName_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                onlineAppName_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int ONLINEDATE_FIELD_NUMBER = 6;
        private com.google.protobuf.Timestamp onlineDate_;

        /**
         * <pre>
         * *接受消息的时间
         * </pre>
         *
         * <code>.google.protobuf.Timestamp onlineDate = 6;</code>
         *
         * @return Whether the onlineDate field is set.
         */
        @java.lang.Override
        public boolean hasOnlineDate() {
            return onlineDate_ != null;
        }

        /**
         * <pre>
         * *接受消息的时间
         * </pre>
         *
         * <code>.google.protobuf.Timestamp onlineDate = 6;</code>
         *
         * @return The onlineDate.
         */
        @java.lang.Override
        public com.google.protobuf.Timestamp getOnlineDate() {
            return onlineDate_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : onlineDate_;
        }

        /**
         * <pre>
         * *接受消息的时间
         * </pre>
         *
         * <code>.google.protobuf.Timestamp onlineDate = 6;</code>
         */
        @java.lang.Override
        public com.google.protobuf.TimestampOrBuilder getOnlineDateOrBuilder() {
            return getOnlineDate();
        }

        public static final int ISACTIVE_FIELD_NUMBER = 7;
        private boolean isActive_;

        /**
         * <pre>
         * *是否上线
         * </pre>
         *
         * <code>bool isActive = 7;</code>
         *
         * @return The isActive.
         */
        @java.lang.Override
        public boolean getIsActive() {
            return isActive_;
        }

        private byte memoizedIsInitialized = -1;

        @java.lang.Override
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        @java.lang.Override
        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            if (type_ != MessageTypeProto.MessageType.LOGGER_COLLECTOR.getNumber()) {
                output.writeEnum(2, type_);
            }
            if (msgId_ != 0L) {
                output.writeInt64(3, msgId_);
            }
            if (!getMsgBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 4, msg_);
            }
            if (!getOnlineAppNameBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 5, onlineAppName_);
            }
            if (onlineDate_ != null) {
                output.writeMessage(6, getOnlineDate());
            }
            if (isActive_ != false) {
                output.writeBool(7, isActive_);
            }
            unknownFields.writeTo(output);
        }

        @java.lang.Override
        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            if (type_ != MessageTypeProto.MessageType.LOGGER_COLLECTOR.getNumber()) {
                size += com.google.protobuf.CodedOutputStream
                        .computeEnumSize(2, type_);
            }
            if (msgId_ != 0L) {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt64Size(3, msgId_);
            }
            if (!getMsgBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, msg_);
            }
            if (!getOnlineAppNameBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, onlineAppName_);
            }
            if (onlineDate_ != null) {
                size += com.google.protobuf.CodedOutputStream
                        .computeMessageSize(6, getOnlineDate());
            }
            if (isActive_ != false) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBoolSize(7, isActive_);
            }
            size += unknownFields.getSerializedSize();
            memoizedSize = size;
            return size;
        }

        @java.lang.Override
        public boolean equals(final java.lang.Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof MessageBodyProto.MessageBody)) {
                return super.equals(obj);
            }
            MessageBodyProto.MessageBody other = (MessageBodyProto.MessageBody) obj;

            if (type_ != other.type_) return false;
            if (getMsgId()
                    != other.getMsgId()) return false;
            if (!getMsg()
                    .equals(other.getMsg())) return false;
            if (!getOnlineAppName()
                    .equals(other.getOnlineAppName())) return false;
            if (hasOnlineDate() != other.hasOnlineDate()) return false;
            if (hasOnlineDate()) {
                if (!getOnlineDate()
                        .equals(other.getOnlineDate())) return false;
            }
            if (getIsActive()
                    != other.getIsActive()) return false;
            if (!unknownFields.equals(other.unknownFields)) return false;
            return true;
        }

        @java.lang.Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            hash = (37 * hash) + TYPE_FIELD_NUMBER;
            hash = (53 * hash) + type_;
            hash = (37 * hash) + MSGID_FIELD_NUMBER;
            hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                    getMsgId());
            hash = (37 * hash) + MSG_FIELD_NUMBER;
            hash = (53 * hash) + getMsg().hashCode();
            hash = (37 * hash) + ONLINEAPPNAME_FIELD_NUMBER;
            hash = (53 * hash) + getOnlineAppName().hashCode();
            if (hasOnlineDate()) {
                hash = (37 * hash) + ONLINEDATE_FIELD_NUMBER;
                hash = (53 * hash) + getOnlineDate().hashCode();
            }
            hash = (37 * hash) + ISACTIVE_FIELD_NUMBER;
            hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
                    getIsActive());
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public static MessageBodyProto.MessageBody parseFrom(
                java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static MessageBodyProto.MessageBody parseFrom(
                java.nio.ByteBuffer data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static MessageBodyProto.MessageBody parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static MessageBodyProto.MessageBody parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static MessageBodyProto.MessageBody parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static MessageBodyProto.MessageBody parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static MessageBodyProto.MessageBody parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static MessageBodyProto.MessageBody parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static MessageBodyProto.MessageBody parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }

        public static MessageBodyProto.MessageBody parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }

        public static MessageBodyProto.MessageBody parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static MessageBodyProto.MessageBody parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        @java.lang.Override
        public Builder newBuilderForType() {
            return newBuilder();
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(MessageBodyProto.MessageBody prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        @java.lang.Override
        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        /**
         * Protobuf type {@code com.javayh.agent.rpc.MessageBody}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:com.javayh.agent.rpc.MessageBody)
                MessageBodyProto.MessageBodyOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return MessageBodyProto.internal_static_com_javayh_agent_rpc_MessageBody_descriptor;
            }

            @java.lang.Override
            protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return MessageBodyProto.internal_static_com_javayh_agent_rpc_MessageBody_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                MessageBodyProto.MessageBody.class, MessageBodyProto.MessageBody.Builder.class);
            }

            // Construct using com.javayh.agent.common.bean.proto.MessageBodyProto.MessageBody.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3
                        .alwaysUseFieldBuilders) {
                }
            }

            @java.lang.Override
            public Builder clear() {
                super.clear();
                type_ = 0;

                msgId_ = 0L;

                msg_ = "";

                onlineAppName_ = "";

                if (onlineDateBuilder_ == null) {
                    onlineDate_ = null;
                } else {
                    onlineDate_ = null;
                    onlineDateBuilder_ = null;
                }
                isActive_ = false;

                return this;
            }

            @java.lang.Override
            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return MessageBodyProto.internal_static_com_javayh_agent_rpc_MessageBody_descriptor;
            }

            @java.lang.Override
            public MessageBodyProto.MessageBody getDefaultInstanceForType() {
                return MessageBodyProto.MessageBody.getDefaultInstance();
            }

            @java.lang.Override
            public MessageBodyProto.MessageBody build() {
                MessageBodyProto.MessageBody result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            @java.lang.Override
            public MessageBodyProto.MessageBody buildPartial() {
                MessageBodyProto.MessageBody result = new MessageBodyProto.MessageBody(this);
                result.type_ = type_;
                result.msgId_ = msgId_;
                result.msg_ = msg_;
                result.onlineAppName_ = onlineAppName_;
                if (onlineDateBuilder_ == null) {
                    result.onlineDate_ = onlineDate_;
                } else {
                    result.onlineDate_ = onlineDateBuilder_.build();
                }
                result.isActive_ = isActive_;
                onBuilt();
                return result;
            }

            @java.lang.Override
            public Builder clone() {
                return super.clone();
            }

            @java.lang.Override
            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return super.setField(field, value);
            }

            @java.lang.Override
            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field) {
                return super.clearField(field);
            }

            @java.lang.Override
            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return super.clearOneof(oneof);
            }

            @java.lang.Override
            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, java.lang.Object value) {
                return super.setRepeatedField(field, index, value);
            }

            @java.lang.Override
            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return super.addRepeatedField(field, value);
            }

            @java.lang.Override
            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof MessageBodyProto.MessageBody) {
                    return mergeFrom((MessageBodyProto.MessageBody) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(MessageBodyProto.MessageBody other) {
                if (other == MessageBodyProto.MessageBody.getDefaultInstance()) return this;
                if (other.type_ != 0) {
                    setTypeValue(other.getTypeValue());
                }
                if (other.getMsgId() != 0L) {
                    setMsgId(other.getMsgId());
                }
                if (!other.getMsg().isEmpty()) {
                    msg_ = other.msg_;
                    onChanged();
                }
                if (!other.getOnlineAppName().isEmpty()) {
                    onlineAppName_ = other.onlineAppName_;
                    onChanged();
                }
                if (other.hasOnlineDate()) {
                    mergeOnlineDate(other.getOnlineDate());
                }
                if (other.getIsActive() != false) {
                    setIsActive(other.getIsActive());
                }
                this.mergeUnknownFields(other.unknownFields);
                onChanged();
                return this;
            }

            @java.lang.Override
            public final boolean isInitialized() {
                return true;
            }

            @java.lang.Override
            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                MessageBodyProto.MessageBody parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (MessageBodyProto.MessageBody) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            private int type_ = 0;

            /**
             * <pre>
             * 消息类型字段
             * </pre>
             *
             * <code>.com.javayh.agent.rpc.MessageType type = 2;</code>
             *
             * @return The enum numeric value on the wire for type.
             */
            @java.lang.Override
            public int getTypeValue() {
                return type_;
            }

            /**
             * <pre>
             * 消息类型字段
             * </pre>
             *
             * <code>.com.javayh.agent.rpc.MessageType type = 2;</code>
             *
             * @param value The enum numeric value on the wire for type to set.
             * @return This builder for chaining.
             */
            public Builder setTypeValue(int value) {

                type_ = value;
                onChanged();
                return this;
            }

            /**
             * <pre>
             * 消息类型字段
             * </pre>
             *
             * <code>.com.javayh.agent.rpc.MessageType type = 2;</code>
             *
             * @return The type.
             */
            @java.lang.Override
            public MessageTypeProto.MessageType getType() {
                @SuppressWarnings("deprecation")
                MessageTypeProto.MessageType result = MessageTypeProto.MessageType.valueOf(type_);
                return result == null ? MessageTypeProto.MessageType.UNRECOGNIZED : result;
            }

            /**
             * <pre>
             * 消息类型字段
             * </pre>
             *
             * <code>.com.javayh.agent.rpc.MessageType type = 2;</code>
             *
             * @param value The type to set.
             * @return This builder for chaining.
             */
            public Builder setType(MessageTypeProto.MessageType value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                type_ = value.getNumber();
                onChanged();
                return this;
            }

            /**
             * <pre>
             * 消息类型字段
             * </pre>
             *
             * <code>.com.javayh.agent.rpc.MessageType type = 2;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearType() {

                type_ = 0;
                onChanged();
                return this;
            }

            private long msgId_;

            /**
             * <pre>
             * *服务标识
             * </pre>
             *
             * <code>int64 msgId = 3;</code>
             *
             * @return The msgId.
             */
            @java.lang.Override
            public long getMsgId() {
                return msgId_;
            }

            /**
             * <pre>
             * *服务标识
             * </pre>
             *
             * <code>int64 msgId = 3;</code>
             *
             * @param value The msgId to set.
             * @return This builder for chaining.
             */
            public Builder setMsgId(long value) {

                msgId_ = value;
                onChanged();
                return this;
            }

            /**
             * <pre>
             * *服务标识
             * </pre>
             *
             * <code>int64 msgId = 3;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearMsgId() {

                msgId_ = 0L;
                onChanged();
                return this;
            }

            private java.lang.Object msg_ = "";

            /**
             * <pre>
             * *发送的消息
             * </pre>
             *
             * <code>string msg = 4;</code>
             *
             * @return The msg.
             */
            public java.lang.String getMsg() {
                java.lang.Object ref = msg_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    msg_ = s;
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }

            /**
             * <pre>
             * *发送的消息
             * </pre>
             *
             * <code>string msg = 4;</code>
             *
             * @return The bytes for msg.
             */
            public com.google.protobuf.ByteString
            getMsgBytes() {
                java.lang.Object ref = msg_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    msg_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <pre>
             * *发送的消息
             * </pre>
             *
             * <code>string msg = 4;</code>
             *
             * @param value The msg to set.
             * @return This builder for chaining.
             */
            public Builder setMsg(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                msg_ = value;
                onChanged();
                return this;
            }

            /**
             * <pre>
             * *发送的消息
             * </pre>
             *
             * <code>string msg = 4;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearMsg() {

                msg_ = getDefaultInstance().getMsg();
                onChanged();
                return this;
            }

            /**
             * <pre>
             * *发送的消息
             * </pre>
             *
             * <code>string msg = 4;</code>
             *
             * @param value The bytes for msg to set.
             * @return This builder for chaining.
             */
            public Builder setMsgBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                msg_ = value;
                onChanged();
                return this;
            }

            private java.lang.Object onlineAppName_ = "";

            /**
             * <pre>
             * *服务名
             * </pre>
             *
             * <code>string onlineAppName = 5;</code>
             *
             * @return The onlineAppName.
             */
            public java.lang.String getOnlineAppName() {
                java.lang.Object ref = onlineAppName_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    onlineAppName_ = s;
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }

            /**
             * <pre>
             * *服务名
             * </pre>
             *
             * <code>string onlineAppName = 5;</code>
             *
             * @return The bytes for onlineAppName.
             */
            public com.google.protobuf.ByteString
            getOnlineAppNameBytes() {
                java.lang.Object ref = onlineAppName_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    onlineAppName_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <pre>
             * *服务名
             * </pre>
             *
             * <code>string onlineAppName = 5;</code>
             *
             * @param value The onlineAppName to set.
             * @return This builder for chaining.
             */
            public Builder setOnlineAppName(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                onlineAppName_ = value;
                onChanged();
                return this;
            }

            /**
             * <pre>
             * *服务名
             * </pre>
             *
             * <code>string onlineAppName = 5;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearOnlineAppName() {

                onlineAppName_ = getDefaultInstance().getOnlineAppName();
                onChanged();
                return this;
            }

            /**
             * <pre>
             * *服务名
             * </pre>
             *
             * <code>string onlineAppName = 5;</code>
             *
             * @param value The bytes for onlineAppName to set.
             * @return This builder for chaining.
             */
            public Builder setOnlineAppNameBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                onlineAppName_ = value;
                onChanged();
                return this;
            }

            private com.google.protobuf.Timestamp onlineDate_;
            private com.google.protobuf.SingleFieldBuilderV3<
                    com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> onlineDateBuilder_;

            /**
             * <pre>
             * *接受消息的时间
             * </pre>
             *
             * <code>.google.protobuf.Timestamp onlineDate = 6;</code>
             *
             * @return Whether the onlineDate field is set.
             */
            public boolean hasOnlineDate() {
                return onlineDateBuilder_ != null || onlineDate_ != null;
            }

            /**
             * <pre>
             * *接受消息的时间
             * </pre>
             *
             * <code>.google.protobuf.Timestamp onlineDate = 6;</code>
             *
             * @return The onlineDate.
             */
            public com.google.protobuf.Timestamp getOnlineDate() {
                if (onlineDateBuilder_ == null) {
                    return onlineDate_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : onlineDate_;
                } else {
                    return onlineDateBuilder_.getMessage();
                }
            }

            /**
             * <pre>
             * *接受消息的时间
             * </pre>
             *
             * <code>.google.protobuf.Timestamp onlineDate = 6;</code>
             */
            public Builder setOnlineDate(com.google.protobuf.Timestamp value) {
                if (onlineDateBuilder_ == null) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    onlineDate_ = value;
                    onChanged();
                } else {
                    onlineDateBuilder_.setMessage(value);
                }

                return this;
            }

            /**
             * <pre>
             * *接受消息的时间
             * </pre>
             *
             * <code>.google.protobuf.Timestamp onlineDate = 6;</code>
             */
            public Builder setOnlineDate(
                    com.google.protobuf.Timestamp.Builder builderForValue) {
                if (onlineDateBuilder_ == null) {
                    onlineDate_ = builderForValue.build();
                    onChanged();
                } else {
                    onlineDateBuilder_.setMessage(builderForValue.build());
                }

                return this;
            }

            /**
             * <pre>
             * *接受消息的时间
             * </pre>
             *
             * <code>.google.protobuf.Timestamp onlineDate = 6;</code>
             */
            public Builder mergeOnlineDate(com.google.protobuf.Timestamp value) {
                if (onlineDateBuilder_ == null) {
                    if (onlineDate_ != null) {
                        onlineDate_ =
                                com.google.protobuf.Timestamp.newBuilder(onlineDate_).mergeFrom(value).buildPartial();
                    } else {
                        onlineDate_ = value;
                    }
                    onChanged();
                } else {
                    onlineDateBuilder_.mergeFrom(value);
                }

                return this;
            }

            /**
             * <pre>
             * *接受消息的时间
             * </pre>
             *
             * <code>.google.protobuf.Timestamp onlineDate = 6;</code>
             */
            public Builder clearOnlineDate() {
                if (onlineDateBuilder_ == null) {
                    onlineDate_ = null;
                    onChanged();
                } else {
                    onlineDate_ = null;
                    onlineDateBuilder_ = null;
                }

                return this;
            }

            /**
             * <pre>
             * *接受消息的时间
             * </pre>
             *
             * <code>.google.protobuf.Timestamp onlineDate = 6;</code>
             */
            public com.google.protobuf.Timestamp.Builder getOnlineDateBuilder() {

                onChanged();
                return getOnlineDateFieldBuilder().getBuilder();
            }

            /**
             * <pre>
             * *接受消息的时间
             * </pre>
             *
             * <code>.google.protobuf.Timestamp onlineDate = 6;</code>
             */
            public com.google.protobuf.TimestampOrBuilder getOnlineDateOrBuilder() {
                if (onlineDateBuilder_ != null) {
                    return onlineDateBuilder_.getMessageOrBuilder();
                } else {
                    return onlineDate_ == null ?
                            com.google.protobuf.Timestamp.getDefaultInstance() : onlineDate_;
                }
            }

            /**
             * <pre>
             * *接受消息的时间
             * </pre>
             *
             * <code>.google.protobuf.Timestamp onlineDate = 6;</code>
             */
            private com.google.protobuf.SingleFieldBuilderV3<
                    com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>
            getOnlineDateFieldBuilder() {
                if (onlineDateBuilder_ == null) {
                    onlineDateBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
                            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                            getOnlineDate(),
                            getParentForChildren(),
                            isClean());
                    onlineDate_ = null;
                }
                return onlineDateBuilder_;
            }

            private boolean isActive_;

            /**
             * <pre>
             * *是否上线
             * </pre>
             *
             * <code>bool isActive = 7;</code>
             *
             * @return The isActive.
             */
            @java.lang.Override
            public boolean getIsActive() {
                return isActive_;
            }

            /**
             * <pre>
             * *是否上线
             * </pre>
             *
             * <code>bool isActive = 7;</code>
             *
             * @param value The isActive to set.
             * @return This builder for chaining.
             */
            public Builder setIsActive(boolean value) {

                isActive_ = value;
                onChanged();
                return this;
            }

            /**
             * <pre>
             * *是否上线
             * </pre>
             *
             * <code>bool isActive = 7;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearIsActive() {

                isActive_ = false;
                onChanged();
                return this;
            }

            @java.lang.Override
            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.setUnknownFields(unknownFields);
            }

            @java.lang.Override
            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.mergeUnknownFields(unknownFields);
            }


            // @@protoc_insertion_point(builder_scope:com.javayh.agent.rpc.MessageBody)
        }

        // @@protoc_insertion_point(class_scope:com.javayh.agent.rpc.MessageBody)
        private static final MessageBodyProto.MessageBody DEFAULT_INSTANCE;

        static {
            DEFAULT_INSTANCE = new MessageBodyProto.MessageBody();
        }

        public static MessageBodyProto.MessageBody getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        private static final com.google.protobuf.Parser<MessageBody>
                PARSER = new com.google.protobuf.AbstractParser<MessageBody>() {
            @java.lang.Override
            public MessageBody parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return new MessageBody(input, extensionRegistry);
            }
        };

        public static com.google.protobuf.Parser<MessageBody> parser() {
            return PARSER;
        }

        @java.lang.Override
        public com.google.protobuf.Parser<MessageBody> getParserForType() {
            return PARSER;
        }

        @java.lang.Override
        public MessageBodyProto.MessageBody getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

    }

    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_com_javayh_agent_rpc_MessageBody_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_com_javayh_agent_rpc_MessageBody_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }

    private static com.google.protobuf.Descriptors.FileDescriptor
            descriptor;

    static {
        java.lang.String[] descriptorData = {
                "\n\021MessageBody.proto\022\024com.javayh.agent.rp" +
                        "c\032\037google/protobuf/timestamp.proto\032\021Mess" +
                        "ageType.proto\"\263\001\n\013MessageBody\022/\n\004type\030\002 " +
                        "\001(\0162!.com.javayh.agent.rpc.MessageType\022\r" +
                        "\n\005msgId\030\003 \001(\003\022\013\n\003msg\030\004 \001(\t\022\025\n\ronlineAppN" +
                        "ame\030\005 \001(\t\022.\n\nonlineDate\030\006 \001(\0132\032.google.p" +
                        "rotobuf.Timestamp\022\020\n\010isActive\030\007 \001(\010B\022B\020M" +
                        "essageBodyProtob\006proto3"
        };
        descriptor = com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[]{
                                com.google.protobuf.TimestampProto.getDescriptor(),
                                MessageTypeProto.getDescriptor(),
                        });
        internal_static_com_javayh_agent_rpc_MessageBody_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_com_javayh_agent_rpc_MessageBody_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_com_javayh_agent_rpc_MessageBody_descriptor,
                new java.lang.String[]{"Type", "MsgId", "Msg", "OnlineAppName", "OnlineDate", "IsActive",});
        com.google.protobuf.TimestampProto.getDescriptor();
        MessageTypeProto.getDescriptor();
    }

    // @@protoc_insertion_point(outer_class_scope)
}
