// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MessageBody.proto

package com.javayh.agent.common.bean.proto;

public final class MessageBodyProto {
    private MessageBodyProto() {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
                (com.google.protobuf.ExtensionRegistryLite) registry);
    }

    public interface MessageBodyOrBuilder extends
            // @@protoc_insertion_point(interface_extends:com.javayh.agent.rpc.MessageBody)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <pre>
         * *服务标识
         * </pre>
         *
         * <code>int64 msgId = 1;</code>
         *
         * @return The msgId.
         */
        long getMsgId();

        /**
         * <pre>
         * *发送的消息
         * </pre>
         *
         * <code>string msg = 2;</code>
         *
         * @return The msg.
         */
        String getMsg();

        /**
         * <pre>
         * *发送的消息
         * </pre>
         *
         * <code>string msg = 2;</code>
         *
         * @return The bytes for msg.
         */
        com.google.protobuf.ByteString
        getMsgBytes();

        /**
         * <pre>
         * *服务名
         * </pre>
         *
         * <code>string appName = 3;</code>
         *
         * @return The appName.
         */
        String getAppName();

        /**
         * <pre>
         * *服务名
         * </pre>
         *
         * <code>string appName = 3;</code>
         *
         * @return The bytes for appName.
         */
        com.google.protobuf.ByteString
        getAppNameBytes();

        /**
         * <pre>
         * *接受消息的时间
         * </pre>
         *
         * <code>.google.protobuf.Timestamp createDate = 4;</code>
         *
         * @return Whether the createDate field is set.
         */
        boolean hasCreateDate();

        /**
         * <pre>
         * *接受消息的时间
         * </pre>
         *
         * <code>.google.protobuf.Timestamp createDate = 4;</code>
         *
         * @return The createDate.
         */
        com.google.protobuf.Timestamp getCreateDate();

        /**
         * <pre>
         * *接受消息的时间
         * </pre>
         *
         * <code>.google.protobuf.Timestamp createDate = 4;</code>
         */
        com.google.protobuf.TimestampOrBuilder getCreateDateOrBuilder();

        /**
         * <pre>
         * *是否在线
         * </pre>
         *
         * <code>bool isActive = 5;</code>
         *
         * @return The isActive.
         */
        boolean getIsActive();
    }

    /**
     * Protobuf type {@code com.javayh.agent.rpc.MessageBody}
     */
    public static final class MessageBody extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:com.javayh.agent.rpc.MessageBody)
            MessageBodyOrBuilder {
        private static final long serialVersionUID = 0L;

        // Use MessageBody.newBuilder() to construct.
        private MessageBody(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }

        private MessageBody() {
            msg_ = "";
            appName_ = "";
        }

        @Override
        @SuppressWarnings({"unused"})
        protected Object newInstance(
                UnusedPrivateParameter unused) {
            return new MessageBody();
        }

        @Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return this.unknownFields;
        }

        private MessageBody(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            if (extensionRegistry == null) {
                throw new NullPointerException();
            }
            com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                    com.google.protobuf.UnknownFieldSet.newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        case 8: {

                            msgId_ = input.readInt64();
                            break;
                        }
                        case 18: {
                            String s = input.readStringRequireUtf8();

                            msg_ = s;
                            break;
                        }
                        case 26: {
                            String s = input.readStringRequireUtf8();

                            appName_ = s;
                            break;
                        }
                        case 34: {
                            com.google.protobuf.Timestamp.Builder subBuilder = null;
                            if (createDate_ != null) {
                                subBuilder = createDate_.toBuilder();
                            }
                            createDate_ = input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
                            if (subBuilder != null) {
                                subBuilder.mergeFrom(createDate_);
                                createDate_ = subBuilder.buildPartial();
                            }

                            break;
                        }
                        case 40: {

                            isActive_ = input.readBool();
                            break;
                        }
                        default: {
                            if (!parseUnknownField(
                                    input, unknownFields, extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e).setUnfinishedMessage(this);
            } finally {
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return MessageBodyProto.internal_static_com_javayh_agent_rpc_MessageBody_descriptor;
        }

        @Override
        protected FieldAccessorTable
        internalGetFieldAccessorTable() {
            return MessageBodyProto.internal_static_com_javayh_agent_rpc_MessageBody_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            MessageBody.class, Builder.class);
        }

        public static final int MSGID_FIELD_NUMBER = 1;
        private long msgId_;

        /**
         * <pre>
         * *服务标识
         * </pre>
         *
         * <code>int64 msgId = 1;</code>
         *
         * @return The msgId.
         */
        @Override
        public long getMsgId() {
            return msgId_;
        }

        public static final int MSG_FIELD_NUMBER = 2;
        private volatile Object msg_;

        /**
         * <pre>
         * *发送的消息
         * </pre>
         *
         * <code>string msg = 2;</code>
         *
         * @return The msg.
         */
        @Override
        public String getMsg() {
            Object ref = msg_;
            if (ref instanceof String) {
                return (String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                msg_ = s;
                return s;
            }
        }

        /**
         * <pre>
         * *发送的消息
         * </pre>
         *
         * <code>string msg = 2;</code>
         *
         * @return The bytes for msg.
         */
        @Override
        public com.google.protobuf.ByteString
        getMsgBytes() {
            Object ref = msg_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (String) ref);
                msg_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int APPNAME_FIELD_NUMBER = 3;
        private volatile Object appName_;

        /**
         * <pre>
         * *服务名
         * </pre>
         *
         * <code>string appName = 3;</code>
         *
         * @return The appName.
         */
        @Override
        public String getAppName() {
            Object ref = appName_;
            if (ref instanceof String) {
                return (String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                appName_ = s;
                return s;
            }
        }

        /**
         * <pre>
         * *服务名
         * </pre>
         *
         * <code>string appName = 3;</code>
         *
         * @return The bytes for appName.
         */
        @Override
        public com.google.protobuf.ByteString
        getAppNameBytes() {
            Object ref = appName_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (String) ref);
                appName_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int CREATEDATE_FIELD_NUMBER = 4;
        private com.google.protobuf.Timestamp createDate_;

        /**
         * <pre>
         * *接受消息的时间
         * </pre>
         *
         * <code>.google.protobuf.Timestamp createDate = 4;</code>
         *
         * @return Whether the createDate field is set.
         */
        @Override
        public boolean hasCreateDate() {
            return createDate_ != null;
        }

        /**
         * <pre>
         * *接受消息的时间
         * </pre>
         *
         * <code>.google.protobuf.Timestamp createDate = 4;</code>
         *
         * @return The createDate.
         */
        @Override
        public com.google.protobuf.Timestamp getCreateDate() {
            return createDate_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : createDate_;
        }

        /**
         * <pre>
         * *接受消息的时间
         * </pre>
         *
         * <code>.google.protobuf.Timestamp createDate = 4;</code>
         */
        @Override
        public com.google.protobuf.TimestampOrBuilder getCreateDateOrBuilder() {
            return getCreateDate();
        }

        public static final int ISACTIVE_FIELD_NUMBER = 5;
        private boolean isActive_;

        /**
         * <pre>
         * *是否在线
         * </pre>
         *
         * <code>bool isActive = 5;</code>
         *
         * @return The isActive.
         */
        @Override
        public boolean getIsActive() {
            return isActive_;
        }

        private byte memoizedIsInitialized = -1;

        @Override
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        @Override
        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            if (msgId_ != 0L) {
                output.writeInt64(1, msgId_);
            }
            if (!getMsgBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 2, msg_);
            }
            if (!getAppNameBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 3, appName_);
            }
            if (createDate_ != null) {
                output.writeMessage(4, getCreateDate());
            }
            if (isActive_ != false) {
                output.writeBool(5, isActive_);
            }
            unknownFields.writeTo(output);
        }

        @Override
        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            if (msgId_ != 0L) {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt64Size(1, msgId_);
            }
            if (!getMsgBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, msg_);
            }
            if (!getAppNameBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, appName_);
            }
            if (createDate_ != null) {
                size += com.google.protobuf.CodedOutputStream
                        .computeMessageSize(4, getCreateDate());
            }
            if (isActive_ != false) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBoolSize(5, isActive_);
            }
            size += unknownFields.getSerializedSize();
            memoizedSize = size;
            return size;
        }

        @Override
        public boolean equals(final Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof MessageBody)) {
                return super.equals(obj);
            }
            MessageBody other = (MessageBody) obj;

            if (getMsgId()
                    != other.getMsgId()) return false;
            if (!getMsg()
                    .equals(other.getMsg())) return false;
            if (!getAppName()
                    .equals(other.getAppName())) return false;
            if (hasCreateDate() != other.hasCreateDate()) return false;
            if (hasCreateDate()) {
                if (!getCreateDate()
                        .equals(other.getCreateDate())) return false;
            }
            if (getIsActive()
                    != other.getIsActive()) return false;
            if (!unknownFields.equals(other.unknownFields)) return false;
            return true;
        }

        @Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            hash = (37 * hash) + MSGID_FIELD_NUMBER;
            hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                    getMsgId());
            hash = (37 * hash) + MSG_FIELD_NUMBER;
            hash = (53 * hash) + getMsg().hashCode();
            hash = (37 * hash) + APPNAME_FIELD_NUMBER;
            hash = (53 * hash) + getAppName().hashCode();
            if (hasCreateDate()) {
                hash = (37 * hash) + CREATEDATE_FIELD_NUMBER;
                hash = (53 * hash) + getCreateDate().hashCode();
            }
            hash = (37 * hash) + ISACTIVE_FIELD_NUMBER;
            hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
                    getIsActive());
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public static MessageBody parseFrom(
                java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static MessageBody parseFrom(
                java.nio.ByteBuffer data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static MessageBody parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static MessageBody parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static MessageBody parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static MessageBody parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static MessageBody parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static MessageBody parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static MessageBody parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }

        public static MessageBody parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }

        public static MessageBody parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static MessageBody parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        @Override
        public Builder newBuilderForType() {
            return newBuilder();
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(MessageBody prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        @Override
        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @Override
        protected Builder newBuilderForType(
                BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        /**
         * Protobuf type {@code com.javayh.agent.rpc.MessageBody}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:com.javayh.agent.rpc.MessageBody)
                MessageBodyOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return MessageBodyProto.internal_static_com_javayh_agent_rpc_MessageBody_descriptor;
            }

            @Override
            protected FieldAccessorTable
            internalGetFieldAccessorTable() {
                return MessageBodyProto.internal_static_com_javayh_agent_rpc_MessageBody_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                MessageBody.class, Builder.class);
            }

            // Construct using com.javayh.agent.common.bean.proto.MessageBodyProto.MessageBody.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3
                        .alwaysUseFieldBuilders) {
                }
            }

            @Override
            public Builder clear() {
                super.clear();
                msgId_ = 0L;

                msg_ = "";

                appName_ = "";

                if (createDateBuilder_ == null) {
                    createDate_ = null;
                } else {
                    createDate_ = null;
                    createDateBuilder_ = null;
                }
                isActive_ = false;

                return this;
            }

            @Override
            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return MessageBodyProto.internal_static_com_javayh_agent_rpc_MessageBody_descriptor;
            }

            @Override
            public MessageBody getDefaultInstanceForType() {
                return MessageBody.getDefaultInstance();
            }

            @Override
            public MessageBody build() {
                MessageBody result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            @Override
            public MessageBody buildPartial() {
                MessageBody result = new MessageBody(this);
                result.msgId_ = msgId_;
                result.msg_ = msg_;
                result.appName_ = appName_;
                if (createDateBuilder_ == null) {
                    result.createDate_ = createDate_;
                } else {
                    result.createDate_ = createDateBuilder_.build();
                }
                result.isActive_ = isActive_;
                onBuilt();
                return result;
            }

            @Override
            public Builder clone() {
                return super.clone();
            }

            @Override
            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    Object value) {
                return super.setField(field, value);
            }

            @Override
            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field) {
                return super.clearField(field);
            }

            @Override
            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return super.clearOneof(oneof);
            }

            @Override
            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, Object value) {
                return super.setRepeatedField(field, index, value);
            }

            @Override
            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    Object value) {
                return super.addRepeatedField(field, value);
            }

            @Override
            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof MessageBody) {
                    return mergeFrom((MessageBody) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(MessageBody other) {
                if (other == MessageBody.getDefaultInstance()) return this;
                if (other.getMsgId() != 0L) {
                    setMsgId(other.getMsgId());
                }
                if (!other.getMsg().isEmpty()) {
                    msg_ = other.msg_;
                    onChanged();
                }
                if (!other.getAppName().isEmpty()) {
                    appName_ = other.appName_;
                    onChanged();
                }
                if (other.hasCreateDate()) {
                    mergeCreateDate(other.getCreateDate());
                }
                if (other.getIsActive() != false) {
                    setIsActive(other.getIsActive());
                }
                this.mergeUnknownFields(other.unknownFields);
                onChanged();
                return this;
            }

            @Override
            public final boolean isInitialized() {
                return true;
            }

            @Override
            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                MessageBody parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (MessageBody) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            private long msgId_;

            /**
             * <pre>
             * *服务标识
             * </pre>
             *
             * <code>int64 msgId = 1;</code>
             *
             * @return The msgId.
             */
            @Override
            public long getMsgId() {
                return msgId_;
            }

            /**
             * <pre>
             * *服务标识
             * </pre>
             *
             * <code>int64 msgId = 1;</code>
             *
             * @param value The msgId to set.
             * @return This builder for chaining.
             */
            public Builder setMsgId(long value) {

                msgId_ = value;
                onChanged();
                return this;
            }

            /**
             * <pre>
             * *服务标识
             * </pre>
             *
             * <code>int64 msgId = 1;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearMsgId() {

                msgId_ = 0L;
                onChanged();
                return this;
            }

            private Object msg_ = "";

            /**
             * <pre>
             * *发送的消息
             * </pre>
             *
             * <code>string msg = 2;</code>
             *
             * @return The msg.
             */
            public String getMsg() {
                Object ref = msg_;
                if (!(ref instanceof String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    String s = bs.toStringUtf8();
                    msg_ = s;
                    return s;
                } else {
                    return (String) ref;
                }
            }

            /**
             * <pre>
             * *发送的消息
             * </pre>
             *
             * <code>string msg = 2;</code>
             *
             * @return The bytes for msg.
             */
            public com.google.protobuf.ByteString
            getMsgBytes() {
                Object ref = msg_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (String) ref);
                    msg_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <pre>
             * *发送的消息
             * </pre>
             *
             * <code>string msg = 2;</code>
             *
             * @param value The msg to set.
             * @return This builder for chaining.
             */
            public Builder setMsg(
                    String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                msg_ = value;
                onChanged();
                return this;
            }

            /**
             * <pre>
             * *发送的消息
             * </pre>
             *
             * <code>string msg = 2;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearMsg() {

                msg_ = getDefaultInstance().getMsg();
                onChanged();
                return this;
            }

            /**
             * <pre>
             * *发送的消息
             * </pre>
             *
             * <code>string msg = 2;</code>
             *
             * @param value The bytes for msg to set.
             * @return This builder for chaining.
             */
            public Builder setMsgBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                msg_ = value;
                onChanged();
                return this;
            }

            private Object appName_ = "";

            /**
             * <pre>
             * *服务名
             * </pre>
             *
             * <code>string appName = 3;</code>
             *
             * @return The appName.
             */
            public String getAppName() {
                Object ref = appName_;
                if (!(ref instanceof String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    String s = bs.toStringUtf8();
                    appName_ = s;
                    return s;
                } else {
                    return (String) ref;
                }
            }

            /**
             * <pre>
             * *服务名
             * </pre>
             *
             * <code>string appName = 3;</code>
             *
             * @return The bytes for appName.
             */
            public com.google.protobuf.ByteString
            getAppNameBytes() {
                Object ref = appName_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (String) ref);
                    appName_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <pre>
             * *服务名
             * </pre>
             *
             * <code>string appName = 3;</code>
             *
             * @param value The appName to set.
             * @return This builder for chaining.
             */
            public Builder setAppName(
                    String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                appName_ = value;
                onChanged();
                return this;
            }

            /**
             * <pre>
             * *服务名
             * </pre>
             *
             * <code>string appName = 3;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearAppName() {

                appName_ = getDefaultInstance().getAppName();
                onChanged();
                return this;
            }

            /**
             * <pre>
             * *服务名
             * </pre>
             *
             * <code>string appName = 3;</code>
             *
             * @param value The bytes for appName to set.
             * @return This builder for chaining.
             */
            public Builder setAppNameBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                appName_ = value;
                onChanged();
                return this;
            }

            private com.google.protobuf.Timestamp createDate_;
            private com.google.protobuf.SingleFieldBuilderV3<
                    com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> createDateBuilder_;

            /**
             * <pre>
             * *接受消息的时间
             * </pre>
             *
             * <code>.google.protobuf.Timestamp createDate = 4;</code>
             *
             * @return Whether the createDate field is set.
             */
            public boolean hasCreateDate() {
                return createDateBuilder_ != null || createDate_ != null;
            }

            /**
             * <pre>
             * *接受消息的时间
             * </pre>
             *
             * <code>.google.protobuf.Timestamp createDate = 4;</code>
             *
             * @return The createDate.
             */
            public com.google.protobuf.Timestamp getCreateDate() {
                if (createDateBuilder_ == null) {
                    return createDate_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : createDate_;
                } else {
                    return createDateBuilder_.getMessage();
                }
            }

            /**
             * <pre>
             * *接受消息的时间
             * </pre>
             *
             * <code>.google.protobuf.Timestamp createDate = 4;</code>
             */
            public Builder setCreateDate(com.google.protobuf.Timestamp value) {
                if (createDateBuilder_ == null) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    createDate_ = value;
                    onChanged();
                } else {
                    createDateBuilder_.setMessage(value);
                }

                return this;
            }

            /**
             * <pre>
             * *接受消息的时间
             * </pre>
             *
             * <code>.google.protobuf.Timestamp createDate = 4;</code>
             */
            public Builder setCreateDate(
                    com.google.protobuf.Timestamp.Builder builderForValue) {
                if (createDateBuilder_ == null) {
                    createDate_ = builderForValue.build();
                    onChanged();
                } else {
                    createDateBuilder_.setMessage(builderForValue.build());
                }

                return this;
            }

            /**
             * <pre>
             * *接受消息的时间
             * </pre>
             *
             * <code>.google.protobuf.Timestamp createDate = 4;</code>
             */
            public Builder mergeCreateDate(com.google.protobuf.Timestamp value) {
                if (createDateBuilder_ == null) {
                    if (createDate_ != null) {
                        createDate_ =
                                com.google.protobuf.Timestamp.newBuilder(createDate_).mergeFrom(value).buildPartial();
                    } else {
                        createDate_ = value;
                    }
                    onChanged();
                } else {
                    createDateBuilder_.mergeFrom(value);
                }

                return this;
            }

            /**
             * <pre>
             * *接受消息的时间
             * </pre>
             *
             * <code>.google.protobuf.Timestamp createDate = 4;</code>
             */
            public Builder clearCreateDate() {
                if (createDateBuilder_ == null) {
                    createDate_ = null;
                    onChanged();
                } else {
                    createDate_ = null;
                    createDateBuilder_ = null;
                }

                return this;
            }

            /**
             * <pre>
             * *接受消息的时间
             * </pre>
             *
             * <code>.google.protobuf.Timestamp createDate = 4;</code>
             */
            public com.google.protobuf.Timestamp.Builder getCreateDateBuilder() {

                onChanged();
                return getCreateDateFieldBuilder().getBuilder();
            }

            /**
             * <pre>
             * *接受消息的时间
             * </pre>
             *
             * <code>.google.protobuf.Timestamp createDate = 4;</code>
             */
            public com.google.protobuf.TimestampOrBuilder getCreateDateOrBuilder() {
                if (createDateBuilder_ != null) {
                    return createDateBuilder_.getMessageOrBuilder();
                } else {
                    return createDate_ == null ?
                            com.google.protobuf.Timestamp.getDefaultInstance() : createDate_;
                }
            }

            /**
             * <pre>
             * *接受消息的时间
             * </pre>
             *
             * <code>.google.protobuf.Timestamp createDate = 4;</code>
             */
            private com.google.protobuf.SingleFieldBuilderV3<
                    com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>
            getCreateDateFieldBuilder() {
                if (createDateBuilder_ == null) {
                    createDateBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
                            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                            getCreateDate(),
                            getParentForChildren(),
                            isClean());
                    createDate_ = null;
                }
                return createDateBuilder_;
            }

            private boolean isActive_;

            /**
             * <pre>
             * *是否在线
             * </pre>
             *
             * <code>bool isActive = 5;</code>
             *
             * @return The isActive.
             */
            @Override
            public boolean getIsActive() {
                return isActive_;
            }

            /**
             * <pre>
             * *是否在线
             * </pre>
             *
             * <code>bool isActive = 5;</code>
             *
             * @param value The isActive to set.
             * @return This builder for chaining.
             */
            public Builder setIsActive(boolean value) {

                isActive_ = value;
                onChanged();
                return this;
            }

            /**
             * <pre>
             * *是否在线
             * </pre>
             *
             * <code>bool isActive = 5;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearIsActive() {

                isActive_ = false;
                onChanged();
                return this;
            }

            @Override
            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.setUnknownFields(unknownFields);
            }

            @Override
            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.mergeUnknownFields(unknownFields);
            }


            // @@protoc_insertion_point(builder_scope:com.javayh.agent.rpc.MessageBody)
        }

        // @@protoc_insertion_point(class_scope:com.javayh.agent.rpc.MessageBody)
        private static final MessageBody DEFAULT_INSTANCE;

        static {
            DEFAULT_INSTANCE = new MessageBody();
        }

        public static MessageBody getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        private static final com.google.protobuf.Parser<MessageBody>
                PARSER = new com.google.protobuf.AbstractParser<MessageBody>() {
            @Override
            public MessageBody parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return new MessageBody(input, extensionRegistry);
            }
        };

        public static com.google.protobuf.Parser<MessageBody> parser() {
            return PARSER;
        }

        @Override
        public com.google.protobuf.Parser<MessageBody> getParserForType() {
            return PARSER;
        }

        @Override
        public MessageBody getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

    }

    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_com_javayh_agent_rpc_MessageBody_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_com_javayh_agent_rpc_MessageBody_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }

    private static com.google.protobuf.Descriptors.FileDescriptor
            descriptor;

    static {
        String[] descriptorData = {
                "\n\021MessageBody.proto\022\024com.javayh.agent.rp" +
                        "c\032\037google/protobuf/timestamp.proto\"|\n\013Me" +
                        "ssageBody\022\r\n\005msgId\030\001 \001(\003\022\013\n\003msg\030\002 \001(\t\022\017\n" +
                        "\007appName\030\003 \001(\t\022.\n\ncreateDate\030\004 \001(\0132\032.goo" +
                        "gle.protobuf.Timestamp\022\020\n\010isActive\030\005 \001(\010" +
                        "B\022B\020MessageBodyProtob\006proto3"
        };
        descriptor = com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[]{
                                com.google.protobuf.TimestampProto.getDescriptor(),
                        });
        internal_static_com_javayh_agent_rpc_MessageBody_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_com_javayh_agent_rpc_MessageBody_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_com_javayh_agent_rpc_MessageBody_descriptor,
                new String[]{"MsgId", "Msg", "AppName", "CreateDate", "IsActive",});
        com.google.protobuf.TimestampProto.getDescriptor();
    }

    // @@protoc_insertion_point(outer_class_scope)
}
