server:
  servlet:
    context-path: /agent/example


spring:
  application:
    name: agent-example

# rpc 通信协议
data:
  xplorer:
    host: 127.0.0.1
    port: 9098
    app-name: ${spring.application.name}
    show-log: true
    inbound-transfer-rate:
      data-throughput: 100
      period: 45
      initial-delay: 30
    exclude-url:
      - /agent/example/test/agent
      - /agent/example/test/agent


